name: Adam Novotny
markdown: kramdown
permalink: /blog/:year:month:day/:title

collections:
    art:
      output: true
      permalink: /:collection/:year:month:day/:title

    references:
        output: true
        permalink: /:collection/:year:month:day/:title


#
# defaults:
#   - scope:
#
